# Generated by Django 5.2.7 on 2025-10-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=32),
        ),
    ]
