# Generated by Django 5.2.7 on 2025-11-03 07:40

import staff_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0003_rename_last_resend_time_staffprofile_code_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=staff_app.models.default_profile_image, null=True, upload_to=staff_app.models.staff_profile_upload_path),
        ),
    ]
