# Generated by Django 5.2.7 on 2025-11-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0004_staffprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('staff_username', models.CharField(blank=True, max_length=150, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True)),
                ('delete_reason', models.CharField(choices=[('filled', 'Position Filled'), ('expired', 'Expired'), ('company_closed', 'Company Closed'), ('other', 'Other (specify)')], max_length=50)),
                ('delete_reason_other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=100)),
                ('job_number', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('qualification', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField()),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.CharField(choices=[('filled', 'Position Filled'), ('expired', 'Expired'), ('company_closed', 'Company Closed'), ('other', 'Other (specify)')], max_length=50)),
                ('archive_reason_other', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('other', 'Other')], max_length=20)),
                ('experience', models.CharField(help_text='e.g. 2 years', max_length=100)),
                ('job_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('job_description', models.TextField()),
                ('qualification', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
